export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';
export const PRODUCT_DETAILS_CLEAR = 'PRODUCT_DETAILS_CLEAR';

export const CART_CHANGE_QTY_ITEM_SUCCESS = 'CART_CHANGE_QTY_ITEM_SUCCESS';
export const CART_CHANGE_QTY_ITEM_FAILED = 'CART_CHANGE_QTY_ITEM_FAILED';
export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_ADD_FAILED = 'CART_ADD_FAILED';
export const CART_REM_ITEM = 'CART_REM_ITEM';
export const CART_CLEAR_ITEMS = 'CART_CLEAR_ITEMS';

export const CART_LIST_REQUEST = 'CART_LIST_REQUEST';
export const CART_LIST_SUCCESS = 'CART_LIST_SUCCESS';
export const CART_LIST_FAIL = 'CART_LIST_FAIL';
