export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_MODAL_REQUEST = 'PRODUCT_MODAL_REQUEST';
export const PRODUCT_MODAL_SUCCESS = 'PRODUCT_MODAL_SUCCESS';
export const PRODUCT_MODAL_FAIL = 'PRODUCT_MODAL_FAIL';
export const PRODUCT_MODAL_CLEAR = 'PRODUCT_MODAL_CLEAR';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';
export const PRODUCT_DETAILS_CLEAR = 'PRODUCT_DETAILS_CLEAR';

export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST';
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS';
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL';
export const PRODUCT_CREATE_REVIEW_CLEAR = 'PRODUCT_CREATE_REVIEW_CLEAR';

export const CART_CHANGE_QTY_ITEM_SUCCESS = 'CART_CHANGE_QTY_ITEM_SUCCESS';
export const CART_CHANGE_QTY_ITEM_FAILED = 'CART_CHANGE_QTY_ITEM_FAILED';
export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_ADD_FAILED = 'CART_ADD_FAILED';
export const CART_REM_ITEM = 'CART_REM_ITEM';
export const CART_CLEAR_ITEMS = 'CART_CLEAR_ITEMS';

export const CART_LIST_REQUEST = 'CART_LIST_REQUEST';
export const CART_LIST_SUCCESS = 'CART_LIST_SUCCESS';
export const CART_LIST_FAIL = 'CART_LIST_FAIL';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAILED = 'USER_UPDATE_PROFILE_FAILED';

export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';

export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAILED = 'ORDER_CREATE_FAILED';
export const ORDER_CREATE_CLEAR = 'ORDER_CREATE_CLEAR';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAILED = 'ORDER_DETAILS_FAILED';
export const ORDER_DETAILS_CLEAR = 'ORDER_DETAILS_CLEAR';

export const ORDER_PAYMENT_REQUEST = 'ORDER_PAYMENT_REQUEST';
export const ORDER_PAYMENT_SUCCESS = 'ORDER_PAYMENT_SUCCESS';
export const ORDER_PAYMENT_FAILED = 'ORDER_PAYMENT_FAILED';
export const ORDER_PAYMENT_CLEAR = 'ORDER_PAYMENT_CLEAR';

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAILED = 'ORDER_LIST_FAILED';
export const ORDER_LIST_CLEAR = 'ORDER_LIST_CLEAR';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAILED = 'USER_LIST_FAILED';
export const USER_LIST_CLEAR = 'USER_LIST_CLEAR';

export const USER_LIST_DETAILS_REQUEST = 'USER_LIST_DETAILS_REQUEST';
export const USER_LIST_DETAILS_SUCCESS = 'USER_LIST_DETAILS_SUCCESS';
export const USER_LIST_DETAILS_FAILED = 'USER_LIST_DETAILS_FAILED';
export const USER_LIST_DETAILS_CLEAR = 'USER_LIST_DETAILS_CLEAR';

export const USER_UPDATE_ADMIN_REQUEST = 'USER_UPDATE_ADMIN_REQUEST';
export const USER_UPDATE_ADMIN_SUCCESS = 'USER_UPDATE_ADMIN_SUCCESS';
export const USER_UPDATE_ADMIN_FAILED = 'USER_UPDATE_ADMIN_FAILED';

export const PRODUCT_DELETE_ADMIN_REQUEST = 'PRODUCT_DELETE_ADMIN_REQUEST';
export const PRODUCT_DELETE_ADMIN_SUCCESS = 'PRODUCT_DELETE_ADMIN_SUCCESS';
export const PRODUCT_DELETE_ADMIN_FAILED = 'PRODUCT_DELETE_ADMIN_FAILED';

export const PRODUCT_UPDATE_ADMIN_REQUEST = 'PRODUCT_UPDATE_ADMIN_REQUEST';
export const PRODUCT_UPDATE_ADMIN_SUCCESS = 'PRODUCT_UPDATE_ADMIN_SUCCESS';
export const PRODUCT_UPDATE_ADMIN_FAILED = 'PRODUCT_UPDATE_ADMIN_FAILED';

export const PRODUCT_CREATE_ADMIN_REQUEST = 'PRODUCT_CREATE_ADMIN_REQUEST';
export const PRODUCT_CREATE_ADMIN_SUCCESS = 'PRODUCT_CREATE_ADMIN_SUCCESS';
export const PRODUCT_CREATE_ADMIN_FAILED = 'PRODUCT_CREATE_ADMIN_FAILED';

export const PRODUCT_TOP_REQUEST = 'PRODUCT_TOP_REQUEST';
export const PRODUCT_TOP_SUCCESS = 'PRODUCT_TOP_SUCCESS';
export const PRODUCT_TOP_FAILED = 'PRODUCT_TOP_FAILED';

export const PRODUCT_FEATURED_REQUEST = 'PRODUCT_FEATURED_REQUEST';
export const PRODUCT_FEATURED_SUCCESS = 'PRODUCT_FEATURED_SUCCESS';
export const PRODUCT_FEATURED_FAILED = 'PRODUCT_FEATURED_FAILED';

export const SHOP_CATEGORIES_REQUEST = 'SHOP_CATEGORIES_REQUEST';
export const SHOP_CATEGORIES_SUCCESS = 'SHOP_CATEGORIES_SUCCESS';
export const SHOP_CATEGORIES_FAILED = 'SHOP_CATEGORIES_FAILED';

export const SHOP_FEATURED_CATEGORY_REQUEST = 'SHOP_FEATURED_CATEGORY_REQUEST';
export const SHOP_FEATURED_CATEGORY_SUCCESS = 'SHOP_FEATURED_CATEGORY_SUCCESS';
export const SHOP_FEATURED_CATEGORY_FAILED = 'SHOP_FEATURED_CATEGORY_FAILED';

export const SHOP_FEATURED_CATEGORY_PRODUCTS_REQUEST =
  'SHOP_FEATURED_CATEGORY_PRODUCTS_REQUEST';
export const SHOP_FEATURED_CATEGORY_PRODUCTS_SUCCESS =
  'SHOP_FEATURED_CATEGORY_PRODUCTS_SUCCESS';
export const SHOP_FEATURED_CATEGORY_PRODUCTS_FAILED =
  'SHOP_FEATURED_CATEGORY_PRODUCTS_FAILED';

export const SHOP_FEATURED_CATEGORY_ITEMS_REQUEST =
  'SHOP_FEATURED_CATEGORY_ITEMS_REQUEST';
export const SHOP_FEATURED_CATEGORY_ITEMS_SUCCESS =
  'SHOP_FEATURED_CATEGORY_ITEMS_SUCCESS';
export const SHOP_FEATURED_CATEGORY_ITEMS_FAILED =
  'SHOP_FEATURED_CATEGORY_ITEMS_FAILED';

export const SHOP_FEATURED_MESSAGE_REQUEST = 'SHOP_FEATURED_MESSAGE_REQUEST';
export const SHOP_FEATURED_MESSAGE_SUCCESS = 'SHOP_FEATURED_MESSAGE_SUCCESS';
export const SHOP_FEATURED_MESSAGE_FAILED = 'SHOP_FEATURED_MESSAGE_FAILED';
